### ISSUE TITLE
Run container as different user

### ISSUE THREAD

**Issue by sotiris-bos** [sethsimmons/simple-monerod-docker#13]
Hello,

I think by having the ability to run the container as a different user is beneficial from a security standpoint.

I tried to do so but encountered problems probably because the dockerfile sets a user itself.

Is there any chance that this feature be added?

**Comment by sethsimmons** [comment]
The container already runs as a different (non-root) user (`monero`), so there isn't a reason to change it for security.

If you want to change it for some other reason, you can edit the Dockerfile yourself and build the image from there.
